"""Generate packages/core/src/bodies/vsop87-earth.data.ts.

Downloads the official VSOP87D Earth series (Bretagnon & Francou 1988,
public data from the Bureau des Longitudes / CDS), truncates each series to
a fixed number of largest-amplitude terms, and emits a TypeScript table.

VSOP87D gives heliocentric spherical coordinates (L, B, R) referred to the
mean ecliptic and equinox of date — exactly what Meeus ch. 25/32 uses.
Each term contributes A*cos(B + C*tau), tau = julian millennia from J2000 (TT);
series k is multiplied by tau**k. Units: radians (L, B), AU (R).

Truncation keeps well under 0.5 arcsec of solar-longitude error — our
published Sun tolerance is 36 arcsec.
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "scripts" / ".cache" / "VSOP87D.ear"
OUT = ROOT / "packages" / "core" / "src" / "bodies" / "vsop87-earth.data.ts"

URLS = [
    "https://cdsarc.cds.unistra.fr/ftp/VI/81/VSOP87D.ear",
    "https://raw.githubusercontent.com/gmiller123456/vsop87-multilang/master/Raw/VSOP87D.ear",
]

# Terms to keep per series order (files are already sorted by amplitude).
KEEP = {
    "L": [80, 40, 24, 10, 5, 3],
    "B": [10, 5, 3, 2, 1],
    "R": [50, 14, 8, 4, 2],
}
VARIABLE_NAMES = {1: "L", 2: "B", 3: "R"}


def download() -> str:
    if CACHE.exists():
        return CACHE.read_text(encoding="ascii")
    last_error: Exception | None = None
    for url in URLS:
        try:
            with urllib.request.urlopen(url, timeout=60) as response:
                text = response.read().decode("ascii")
            CACHE.parent.mkdir(parents=True, exist_ok=True)
            CACHE.write_text(text, encoding="ascii")
            print(f"downloaded {url} ({len(text)} bytes)")
            return text
        except Exception as error:  # noqa: BLE001 - try the mirror
            print(f"failed {url}: {error}", file=sys.stderr)
            last_error = error
    raise SystemExit(f"could not download VSOP87D.ear: {last_error}")


def parse(text: str) -> dict[str, list[list[tuple[float, float, float]]]]:
    series: dict[str, list[list[tuple[float, float, float]]]] = {
        "L": [], "B": [], "R": [],
    }
    current: list[tuple[float, float, float]] | None = None
    for line in text.splitlines():
        if "VSOP87" in line and "VARIABLE" in line:
            variable = VARIABLE_NAMES[int(line.split("VARIABLE")[1].split()[0])]
            order = int(line.split("*T**")[1].split()[0])
            terms: list[tuple[float, float, float]] = []
            assert len(series[variable]) == order, "series arrived out of order"
            series[variable].append(terms)
            current = terms
        elif current is not None and line.strip():
            fields = line.split()
            a, b, c = (float(x) for x in fields[-3:])
            current.append((a, b, c))
    counts = {v: [len(t) for t in series[v]] for v in series}
    expected_l0 = 559
    if counts["L"][0] != expected_l0:
        raise SystemExit(f"parse sanity failed: L0 has {counts['L'][0]} terms, expected {expected_l0}")
    print(f"parsed term counts: {counts}")
    return series


def emit(series: dict[str, list[list[tuple[float, float, float]]]]) -> None:
    lines = [
        "// Generated by scripts/generate_vsop87_earth.py — DO NOT EDIT BY HAND.",
        "// Source: VSOP87D (Bretagnon & Francou 1988), Earth, heliocentric",
        "// spherical coordinates, mean ecliptic and equinox of date.",
        "// Each term is [A, B, C]: A*cos(B + C*tau), tau = julian millennia",
        "// from J2000 (TT); series k is multiplied by tau**k.",
        "// Units: radians (L, B), AU (R). Truncated to the largest terms:",
        f"// L {KEEP['L']}, B {KEEP['B']}, R {KEEP['R']}.",
        "",
        "export type Vsop87Term = readonly [number, number, number];",
        "export type Vsop87Series = readonly (readonly Vsop87Term[])[];",
    ]
    for variable in ("L", "B", "R"):
        lines.append("")
        lines.append(f"export const EARTH_{variable}: Vsop87Series = [")
        for order, terms in enumerate(series[variable]):
            kept = terms[: KEEP[variable][order]] if order < len(KEEP[variable]) else []
            if not kept:
                continue
            lines.append("  [")
            for a, b, c in kept:
                lines.append(f"    [{a!r}, {b!r}, {c!r}],")
            lines.append("  ],")
        lines.append("];")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    total = sum(min(len(t), KEEP[v][i]) for v in series for i, t in enumerate(series[v]) if i < len(KEEP[v]))
    print(f"wrote {OUT.relative_to(ROOT)} ({total} terms)")


if __name__ == "__main__":
    emit(parse(download()))
